Feature/create-stores
geobeyond/geoserverx pull request #46
Opened 2023-08-18 14:57 UTC by krishnaglodha

Creating vector and raster store

2024-08-18 09:53 UTC, francbartoli requested changes

2024-08-18 09:53 UTC, francbartoli commented on src/geoserverx/_sync/gsx.py
> +    def get_style(self,  style: str) -> StyleModel:
Remove this useless change

2024-08-18 09:53 UTC, francbartoli commented on src/geoserverx/_sync/gsx.py
> +            responses = Client.delete(f"/workspaces/{workspace}/coveragestores/{store}",headers=self.head)
spaces in the signature are not respected

2024-08-18 09:53 UTC, francbartoli commented on src/geoserverx/_sync/gsx.py
> +            responses = Client.delete(f"/workspaces/{workspace}/datastores/{store}",headers=self.head)
Same above

2024-08-18 09:53 UTC, francbartoli commented on src/geoserverx/_sync/gsx.py
> +            data=json.dumps(layer.dict(by_alias=True,exclude_none=True)),
This is not pydantic v2 and also `json.dumps` should not be used

2024-08-18 09:53 UTC, francbartoli commented on src/geoserverx/cli/cli.py
> +        result = client.get_layer(workspace, layer, detail).json()
this is not pydantic v2

2024-08-18 09:53 UTC, francbartoli commented on src/geoserverx/models/coverages_layer.py
> +class _Key(Enum):
Could you add docstring to understand what they represent?

2024-08-18 09:53 UTC, francbartoli commented on src/geoserverx/models/coverages_layer.py
> +class CRSDict(BaseModel):
Why the class name refers to a dictionary?

2024-08-18 09:53 UTC, francbartoli commented on src/geoserverx/models/coverages_layer.py
> +class supportedFormatsString(BaseModel):
Class name should start capitalized

2024-08-18 09:53 UTC, francbartoli commented on src/geoserverx/models/coverages_layer.py
> +class requestSRSString(BaseModel):
Same above

2024-08-18 09:53 UTC, francbartoli commented on src/geoserverx/models/coverages_layer.py
> +class interpolationMethodsString(BaseModel):
Same above

2024-08-18 09:53 UTC, francbartoli commented on src/geoserverx/models/featuretypes_layer.py
> +class CRSetnryDict(BaseModel):
Typo in the class name that is referring surprisingly to a dictionary

2024-08-18 09:53 UTC, francbartoli commented on src/geoserverx/models/featuretypes_layer.py
> +class _Key(Enum):
Is this duplicated?

2024-08-19 08:03 UTC, krishnaglodha commented on src/geoserverx/models/coverages_layer.py
> +class CRSDict(BaseModel):
Replaced the name with `NativeCRS`

2024-08-19 08:08 UTC, krishnaglodha commented on src/geoserverx/models/coverages_layer.py
> +class _Key(Enum):
It is not needed, so I removed it

2024-08-19 08:08 UTC, krishnaglodha commented on src/geoserverx/models/featuretypes_layer.py
> +class _Key(Enum):
Not needed

2024-08-19 08:45 UTC, krishnaglodha commented on src/geoserverx/cli/cli.py
> +        result = client.get_layer(workspace, layer, detail).json()
fixed with model_dump_json

2024-08-19 08:48 UTC, krishnaglodha commented on src/geoserverx/_sync/gsx.py
> +            responses = Client.delete(f"/workspaces/{workspace}/coveragestores/{store}",headers=self.head)
Can you please explain what do you mean by this ?

2024-08-19 08:51 UTC, krishnaglodha commented on src/geoserverx/_sync/gsx.py
> +            data=json.dumps(layer.dict(by_alias=True,exclude_none=True)),
replaced with model_dump

2024-08-19 10:18 UTC, krishnaglodha commented on src/geoserverx/_sync/gsx.py
> +            responses = Client.delete(f"/workspaces/{workspace}/datastores/{store}",headers=self.head)
Can you please explain what do you mean by this ?

2024-08-19 13:20 UTC, francbartoli commented on src/geoserverx/_sync/gsx.py
> +            responses = Client.delete(f"/workspaces/{workspace}/coveragestores/{store}",headers=self.head)
there's no space after the comma, can we definitively enforce a ruff linter into another PR?

2024-08-19 13:20 UTC, francbartoli commented on src/geoserverx/_sync/gsx.py
> +            responses = Client.delete(f"/workspaces/{workspace}/datastores/{store}",headers=self.head)
Same answer above

2024-08-19 13:20 UTC, francbartoli commented
There are conflicts to be resolved

2024-08-20 12:22 UTC, francbartoli commented
I'm merging but the history becomes a mess in such a way

2024-08-20 12:22 UTC, merged