Feature/layer-group
geobeyond/geoserverx pull request #52
Opened 2024-08-19 10:11 UTC by krishnaglodha

Added functions to get the layer group, which are optionally dependent on the workspace name.

2024-08-19 10:25 UTC, krishnaglodha commented
Extra models for `creating new layer group` has been added in this PR. They will be used in upcoming features.

2024-08-19 10:31 UTC, francbartoli requested changes

2024-08-19 10:31 UTC, francbartoli commented on src/geoserverx/models/layer_group.py
> +class PublishedDict(BaseModel):
Does it make sense to refer to a dictionary in the class name?

2024-08-19 10:31 UTC, francbartoli commented on src/geoserverx/models/layer_group.py
> +class PublishablesDict(BaseModel):
same as above

2024-08-19 10:31 UTC, francbartoli commented on src/geoserverx/models/layer_group.py
> +class StyleDict(BaseModel):
same as above

2024-08-19 10:31 UTC, francbartoli commented on src/geoserverx/models/layer_group.py
> +class StylesDict(BaseModel):
Same as above

2024-08-19 10:31 UTC, francbartoli commented on src/geoserverx/models/layer_group.py
> +class BoundsDict(BaseModel):
Same as above

2024-08-19 10:31 UTC, francbartoli commented on tests/test_models.py
>  def test_DataStoreInBulk_connection(good_datastore_in_bulk_connection):
function name lowercase

2024-08-19 10:31 UTC, francbartoli commented on tests/test_models.py
>  def test_NewWorkspace_failure(bad_new_workspace_connection):
Same as above

2024-08-19 10:31 UTC, francbartoli commented on tests/test_models.py
> +def test_WorkspaceModel_connection(good_workspace_model_connection):
Same as above

2024-08-19 10:31 UTC, francbartoli commented on tests/test_models.py
> +def test_WorkspaceModel_failure(bad_workspace_model_connection):
Same as above

2024-08-19 10:31 UTC, francbartoli commented on tests/test_models.py
> +def test_LayerGroupsModel_connection(good_layer_groups_connection):
Same as above

2024-08-19 10:31 UTC, francbartoli commented on tests/test_models.py
> +def test_LayerGroupsModel_failure(bad_layer_groups_connection):
Same as above

2024-08-20 11:31 UTC, francbartoli commented
Can you rebase and fix conflicts as per last changes in develop?

2024-08-23 10:42 UTC, krishnaglodha commented on tests/test_models.py
> -def test_layergroupsmodel_failure(bad_layer_groups_connection):
need to add back these tests again

2024-08-23 10:56 UTC, merged