Feature/get-geofence
geobeyond/geoserverx pull request #56
Opened 2024-08-25 11:01 UTC by krishnaglodha

Added `Get_all_geofence` rule

2024-08-25 11:48 UTC, francbartoli requested changes
I don't see the management of a response when `geofence` is not installed since it's an optional tool

2024-08-25 14:55 UTC, krishnaglodha commented
> I don't see the management of a response when `geofence` is not installed since it's an optional tool

REST endpoint gives `404` 
<img width="856" alt="Screenshot 2024-08-25 at 8 24 14 PM" src="https://github.com/user-attachments/assets/9df904fd-a700-4bd4-8538-c2276039a795">

We are already managing this status code, as following 

<img width="600" alt="Screenshot 2024-08-25 at 8 25 38 PM" src="https://github.com/user-attachments/assets/e32fedd7-deed-4943-8a21-e054e0f89341">

Is that okay ?

2024-08-25 15:34 UTC, francbartoli commented
Maybe using this endpoint `/geoserver/rest/about/status.json`?

2024-08-25 16:07 UTC, krishnaglodha commented
> Maybe using this endpoint `/geoserver/rest/about/status.json`?

we can actually make a function which will check if the extension is available or not..this function then can be called from all geofence and also future extension related endpoints..


e.g. 
```
def check_extension(client,name):
    res = client.get("about/status.json")
    plugins = res.statuss.status
    for plugin_name,href in plugins:
        if plugin_name.contains(name):
            return True    
    return False
```

thoughts ?

2024-08-25 16:42 UTC, francbartoli commented
I would use a function to get the list of modules:

```python
def load_modules(client,name):
    res = client.get("about/status.json")
    modules = [item["name"] for item in res.statuss.status.items()]
    return modules
```
And then use the list for checking if `GeoFence` is present for any `geofence` related call

2024-08-26 02:16 UTC, krishnaglodha commented
> I would use a function to get the list of modules:
> 
> 
> 
> ```python
> 
> def load_modules(client,name):
> 
>     res = client.get("about/status.json")
> 
>     modules = [item["name"] for item in res.statuss.status.items()]
> 
>     return modules
> 
> ```
> 
> And then use the list for checking if `GeoFence` is present for any `geofence` related call

So this function needs to be called in every call we make for the extensions related method right?

2024-09-03 11:34 UTC, francbartoli requested changes
Have you run `ruff` before sending the PR? Why you should not add a step to the CI workflow?

2024-09-03 11:39 UTC, krishnaglodha commented
> Have you run `ruff` before sending the PR? Why you should not add a step to the CI workflow?

We need to make changes to match ruff standards, thus I'm running it manually. 
PS: for this PR, ruff is checked and `All checks passed!`

2024-09-03 11:41 UTC, francbartoli requested changes

2024-09-03 11:41 UTC, francbartoli commented on src/geoserverx/_async/gsx.py
> +from geoserverx.models.geofence import RulesResponse,Rule,NewRule
Are you sure that `ruff` didn't complain in this line?

2024-09-03 12:14 UTC, krishnaglodha commented on src/geoserverx/_async/gsx.py
> +from geoserverx.models.geofence import RulesResponse,Rule,NewRule
<img width="1022" alt="Screenshot 2024-09-03 at 5 44 36 PM" src="https://github.com/user-attachments/assets/f1505e5d-540a-4380-8606-d72e96572689">

no complaints :/

2024-09-06 11:13 UTC, francbartoli requested changes

2024-09-06 11:13 UTC, francbartoli commented on src/geoserverx/_async/gsx.py
>              return GSResponse(code=404, response="Plugin not found")
Why are you returning `404`? That means a logical response if a resource doesn't exist, in this case a GeoFence rule

2024-09-06 11:13 UTC, francbartoli commented on src/geoserverx/_async/gsx.py
>              return GSResponse(code=404, response="Plugin not found")
Same comment above

2024-09-06 11:13 UTC, francbartoli commented on src/geoserverx/_sync/gsx.py
>              return GSResponse(code=404, response="Plugin not found")
Same comment of the async situation

2024-09-06 11:13 UTC, francbartoli commented on src/geoserverx/_sync/gsx.py
>              return GSResponse(code=404, response="Plugin not found")
Same comment

2024-09-06 11:13 UTC, francbartoli commented on src/geoserverx/_sync/gsx.py
>              return GSResponse(code=404, response="Plugin not found")
Same comment

2024-09-06 11:15 UTC, krishnaglodha commented on src/geoserverx/_async/gsx.py
>              return GSResponse(code=404, response="Plugin not found")
I'm returning `404` because the `GeoFence` plugin is missing

2024-09-06 11:23 UTC, francbartoli commented on src/geoserverx/_async/gsx.py
>              return GSResponse(code=404, response="Plugin not found")
`GeoFence` is a dependency and the HTTP client is looking for rules (an array) and so `404` is never expected. If the module is missing then the client request for rules should be even not done so what's the meaning of this returned code?

2024-09-06 11:26 UTC, krishnaglodha commented on src/geoserverx/_async/gsx.py
>              return GSResponse(code=404, response="Plugin not found")
On this line, we are checking if the plugin exists or not. we are not making call to get rules. Only if the `checl_modules` return `True` , then we make call on next line looking for `rules`

2024-09-06 11:26 UTC, krishnaglodha commented on src/geoserverx/_async/gsx.py
> +        responses = await Client.get(
We are making call to look for `rules` here. After `check_module` has returned `True`

2024-09-06 11:30 UTC, francbartoli commented on src/geoserverx/_async/gsx.py
> +        responses = await Client.get(
Indeed, the scope of the function is about looking for rules not modules. The returned code is totally wrong and inconsistent with the scope

2024-09-19 14:03 UTC, francbartoli requested changes

2024-09-19 14:03 UTC, francbartoli commented on src/geoserverx/_async/gsx.py
> +    async def check_modules(self, name) -> Union[bool, GSResponse]:
Are you sure we are returning `GSResponse`?

2024-09-19 14:03 UTC, francbartoli commented on src/geoserverx/_async/gsx.py
>              return GSResponse(code=404, response="Plugin not found")
Is this issue addressed? We are still returning `404`

2024-09-19 14:03 UTC, francbartoli commented on src/geoserverx/_async/gsx.py
> +        if not await self.check_modules("geofence"):
Same issue here

2024-09-20 08:07 UTC, krishnaglodha commented on src/geoserverx/_async/gsx.py
> +    async def check_modules(self, name) -> Union[bool, GSResponse]:
Yes, we get `bool` if the plugin is found or we get GSResponse from `response_recognise` function https://github.com/geobeyond/geoserverx/blob/518210aedeaa247f6efae4641b00b8bbbc4948e7/src/geoserverx/_sync/gsx.py#L81

2024-09-20 08:09 UTC, krishnaglodha commented on src/geoserverx/_async/gsx.py
> +        if not await self.check_modules("geofence"):
I have not fixed all the functions, but only `get_all_geofence_rules` to be sure that the path taken is correct, then I'll replicate it to all the functions on sync as well as async

2024-09-25 17:32 UTC, francbartoli requested changes

2024-09-25 17:32 UTC, francbartoli commented on src/geoserverx/_async/gsx.py
> +                raise Exception(f"'{name}' plugin not found")
Just as a point of improvement here if you raise a custom exception it's better so below you can catch that one and return the `412` while just raise an unexpected generic `Exception`

2024-09-25 17:32 UTC, francbartoli commented on src/geoserverx/_sync/gsx.py
> +                raise Exception(f"'{name}' plugin not found")
Same comment about the custom exception here

2024-09-26 08:46 UTC, krishnaglodha commented on src/geoserverx/_async/gsx.py
> +                raise Exception(f"'{name}' plugin not found")
Are you recommending something like raise ModuleNotFoundError(f"'{name}' plugin not found")

2024-09-26 09:50 UTC, francbartoli commented on src/geoserverx/_async/gsx.py
> +                raise Exception(f"'{name}' plugin not found")
it's pretty much enough `raise GSModuleNotFound(f"'{name}' plugin not found")`

2024-10-08 08:39 UTC, francbartoli commented on src/geoserverx/_async/gsx.py
> +    async def get_all_geofence_rules(self) -> Union[RulesResponse, GSResponse]:
@krishnaglodha the returned type is missing `bool` here given `module_check` can return it?

2024-10-08 08:39 UTC, merged