Feature/workspace
geobeyond/geoserverx pull request #68
Opened 2024-11-05 07:11 UTC by krishnaglodha

Added features of workspaces

2024-11-05 09:34 UTC, krishnaglodha commented
![](https://github.trello.services/images/mini-trello-icon.png) [Workspace related](https://trello.com/c/cpidtmiA/7-workspace-related)

2024-11-06 07:34 UTC, krishnaglodha commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update documentation for workspace](https://trello.com/c/cwDajIJb/8-update-documentation-for-workspace)

2024-11-08 11:36 UTC, ricardogsilva requested changes
This is a good effort, thanks for that!

There are some points that can be improved though - I don't think they are too serious, and hopefully should be quick to fix.

Keep at it!

2024-11-08 11:36 UTC, ricardogsilva commented on docs/pages/async/workspace.md
> +Deleting workspace requires following parameters
`recurse` is implemented as an optional parameter so the docs should not introduce it as being required, as it is misleading

2024-11-08 11:36 UTC, ricardogsilva commented on src/geoserverx/_async/gsx.py
> +    # Delete specific workspaces
This comment (and others like it, which basically repeat the name of the underlying method) seems unnecessary

2024-11-08 11:36 UTC, ricardogsilva commented on src/geoserverx/_async/gsx.py
> +        responses = await Client.delete(f"workspaces/{workspace}?recurse={recurse}")
Can we use a singular noun instead (_e.g._ `response`, and also `result` in the line below)?

Using a plural implies that there are multiple outputs from the method being called, which is a bit misleading

2024-11-08 11:36 UTC, ricardogsilva commented on src/geoserverx/_async/gsx.py
> +            headers=self.head,
This is similar to my other comment, but the inverse :hot_face: 

Can we use a plural noun instead (_e.g._ `self.headers`)?

This is referring to a dict which can contain multiple entries

2024-11-08 11:36 UTC, ricardogsilva commented on src/geoserverx/_sync/gsx.py
> +        print(update_ws.model_dump_json(exclude_unset=True))
This `print` statement seems unnecessary - if you care about keeping it in, maybe make it a debug log output instead?

2024-11-08 11:36 UTC, ricardogsilva commented on src/geoserverx/cli/cli.py
> +    workspace: str = typer.Option(..., help="Workspace name"),
`workspace` is mandatory for this command, so please use a [typer CLI Argument](https://typer.tiangolo.com/tutorial/first-steps/#what-is-a-cli-argument) instead.

In general, when a parameter is mandatory it is more common to have it be an argument - lets keep up with the norm, which makes it easier for users, as it is familiar

This would result in an invocation like:

```diff
-gsx delete-workspace --name myworkspace
+gsx delete-workspace myworkspace
```

2024-11-08 11:36 UTC, ricardogsilva commented on src/geoserverx/cli/cli.py
> +            print(result)
This is a convoluted way to check for an error, which introduces complexity in the code - `result` is converted to a JSON string and then we perform a string-based search for the `"code"`? 

Does `GSResponse` not include some attribute in there which you could check to see if there was a problem?

2024-11-08 11:36 UTC, ricardogsilva commented on src/geoserverx/cli/cli.py
> +    current_name: str = typer.Option(..., help="Current Workspace name"),
Same comment as above, `current_name` ought to be a typer CLI argument, as it is mandatory

2024-11-08 11:36 UTC, ricardogsilva commented on src/geoserverx/cli/cli.py
> +    Add workspace in the Geoserver
Please update this docstring

2024-11-08 11:36 UTC, ricardogsilva commented on src/geoserverx/cli/cli.py
> +            ),
You are sending a `dict` to the `client.update_workspace()` method, which in the respective `gsx.py` file is annotated as expecting a pydantic model instance instead.

2024-11-08 11:36 UTC, ricardogsilva commented on src/geoserverx/cli/cli.py
> +            typer.secho(result, fg=typer.colors.RED)
This is another strange way of finding out if there was an error in the execution. Differently from my previous comment, but here the result gets serialized to a JSON string, then converted back to a dict where we check for the `code` key - again, would `GSResponse`, _i.e._ the type of `result` not have a useful attribute that can be inspected directly?

2024-11-08 11:36 UTC, ricardogsilva commented on tests/conftest.py
> +    return item
Please do not use fixtures for defining a simple dict like this - In my opinion it is sometimes OK to have some duplication in test files, if that makes it easier to understand the code better. 

In this case, going back and forth between the test and conftest files for such a simple construct makes it more cumbersome to follow along.

This comment applies to other fixtures too, not just this one.

If you care about reducing test sizes, maybe use [test parametrization](https://docs.pytest.org/en/stable/how-to/parametrize.html) instead?

2024-11-08 11:36 UTC, ricardogsilva commented on tests/test_models.py
> +        UpdateWorkspace(**bad_update_workspace_connection)
I would not bother writing tests like these. These are just verifying that pydantic models work. We can assume that these are covered by pydantic's own test suites and focus on testing geoserverx' features instead.

Plus, it is less work for us too :wink:

2024-11-08 11:36 UTC, ricardogsilva commented on src/geoserverx/_async/gsx.py
> +            data=update_ws.model_dump_json(exclude_unset=True),
Using `exclude_unset` here seems a bit confusing to me.

Doesn't this mean that if the model has default values for some properties (which we can choose to not provide at initialization time, because they are already the default), then these get discarded? What would be the point in having those default values then?

It seems to make more sense to not use `exclude_unset` and rely on having correct models in the first place.

2024-11-08 13:28 UTC, krishnaglodha commented on docs/pages/async/workspace.md
> +Deleting workspace requires following parameters
Should we write `optional` next to it ?

2024-11-08 13:33 UTC, krishnaglodha commented on src/geoserverx/_async/gsx.py
> +            data=update_ws.model_dump_json(exclude_unset=True),
`exclude_unset` will create dictionary only for things which has values. e.g. in update workspace, user can give either of name , isolated or even both. In case of user giving only either name or isolated, other entry should not be in dict, by using `exclude_unset` it will only contain the entry given.

2024-11-08 14:02 UTC, ricardogsilva commented on docs/pages/async/workspace.md
> +Deleting workspace requires following parameters
My main objection is the use of the word 'requires' in the introduction of the parameters - you can fix it in whatever way reads better for you - you are probably more fluent in english than me :sweat_smile: 

Just don't make it sound like `recurse` is required, when the funcion signature has it as being optional

2024-11-08 14:15 UTC, ricardogsilva commented on src/geoserverx/_async/gsx.py
> +            data=update_ws.model_dump_json(exclude_unset=True),
> exclude_unset will create dictionary only for things which has values

This is not how `exclude_unset` works:

```python
In [1]: import pydantic

In [2]: class Test(pydantic.BaseModel):
   ...:     property_a: str = None
   ...:     property_b: str = "hi there"
   ...:     property_c: str
   ...: 

In [3]: t1 = Test(property_c = "world")

In [4]: t1
Out[4]: Test(property_a=None, property_b='hi there', property_c='world')

In [5]: t1.model_dump_json()
Out[5]: '{"property_a":null,"property_b":"hi there","property_c":"world"}'

In [6]: t1.model_dump_json(exclude_unset=True)
Out[6]: '{"property_c":"world"}'
```

As you can see in the example I posted above, when `t1` is dumped to JSON using the `exclude_unset=True` parameter, then the `property_b` will be absent from the output, even though it has a value.

Maybe in this particular case it can work out OK because both default values in the `UpdateWorkspace` model are set to `None` - but this would very likely lead to a bug if the default value would have been something else.

Also, the code is implying that the GeoServer REST API does not allow changing both the `name` and the `isolated` properties of a workspace in the same request. Is this true? I don't have a GeoServer install at hand to test, but it seems strange that it would behave like that.

Another remark is that there is no mention of the `isolated` parameter on the GeoServer API docs here:

https://docs.geoserver.org/latest/en/api/#1.0.0/workspaces.yaml

Do we want to commit to support upstream undocumented API features? This is another discussion that we can have, but in my opinion we should not be exposing undocumented stuff, as it can go away in a future GeoServer release, and if that happens we will be having a problem towards our users.

2024-11-08 14:22 UTC, ricardogsilva commented on src/geoserverx/_async/gsx.py
> +            data=update_ws.model_dump_json(exclude_unset=True),
Perhaps a better choice would be to use `exclude_none` instead of `exclude_unset`

https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.model_dump_json

2024-11-17 14:07 UTC, krishnaglodha commented on src/geoserverx/cli/cli.py
> +            typer.secho(result, fg=typer.colors.RED)
will fix this in new PR

2024-11-17 14:08 UTC, krishnaglodha commented on tests/conftest.py
> +    return item
will fix this in new PR

2024-11-17 14:08 UTC, krishnaglodha commented on tests/test_models.py
> +        UpdateWorkspace(**bad_update_workspace_connection)
Should I remove these tests ?

2024-11-19 21:03 UTC, krishnaglodha commented on tests/conftest.py
> +    return item
we're using respx at other tests and also using same dict at 3 places, by keeping it in `conftest` we can refer same file thrice, should we keep it like that ?

2024-12-03 13:00 UTC, ricardogsilva requested changes
Good work.

I am requesting some more small changes though, but I'm sure they'll be quick to do. Keep at it :wink:

2024-12-03 13:00 UTC, ricardogsilva commented on docs/pages/async/workspace.md
> +| Isolated | :negative_squared_cross_mark: | `False` |`bool`      |  To define whether to keep workspace as default or not |
The description of `isolated` is not correct.

Additionally, more of a suggestion, I'd remove the part 'To define whether to' and just go with the rest of the sentence

2024-12-03 13:00 UTC, ricardogsilva commented on docs/pages/async/workspace.md
> +| update | :negative_squared_cross_mark:  |  [`UpdateWorkspaceInfo`](https://github.com/geobeyond/geoserverx/blob/b7757c9f0130864b06c40c2faa17afc841fc705f/src/geoserverx/models/workspace.py#L42)
The `update` parameter is required

2024-12-03 13:00 UTC, ricardogsilva commented on docs/pages/cli/workspace.md
> +  --workspace TEXT        Workspace name  [required]
This should become an argument, not an optional parameter

2024-12-03 13:00 UTC, ricardogsilva commented on docs/pages/cli/workspace.md
> +* --current_name - name of workspace
This is called `--workspace` above and now referred to as `--current_name`

2024-12-03 13:00 UTC, ricardogsilva commented on docs/pages/cli/workspace.md
> +  --current-name TEXT         Current Workspace name  [required]
This should become an argument, not an optional parameter

2024-12-03 13:00 UTC, ricardogsilva commented on docs/pages/sync/workspace.md
> +| Isolated | :negative_squared_cross_mark: | `False` |`bool`      |  To define whether to keep workspace as default or not |
Same comment as above, description for `Isolated` is not correct. Also, as an additional nitpick, please use the actual name of each parameter, including the correct casing (_i.e._ don't capitalize the words)

2024-12-03 13:00 UTC, ricardogsilva commented on docs/pages/sync/workspace.md
> +| update | :negative_squared_cross_mark:  |  [`UpdateWorkspaceInfo`](https://github.com/geobeyond/geoserverx/blob/b7757c9f0130864b06c40c2faa17afc841fc705f/src/geoserverx/models/workspace.py#L42)
The `update` parameter is required

2024-12-03 13:00 UTC, ricardogsilva commented on src/geoserverx/_async/gsx.py
> +        Client = self.http_client
Please do not use a capitalized variable name unless you are referring to a type, as this breaks the usual way variables are named in Python. So in this case this would be `client` instead of `Client` because it refers to an instance of a class, and not the class itself.

Even better would be to avoid creating a new variable for such a short function. This is used only once, so for simplicity I'd not bother with defining this `client` variable and just use its corresponding value below

2024-12-03 13:00 UTC, ricardogsilva commented on src/geoserverx/_async/gsx.py
> +        response = await Client.delete(f"workspaces/{workspace}?recurse={recurse}")
Since we are using httpx, let's avoid creating the query string manually and use its cleaner way to specify a request's query parameters (which is to use a dict), like this:

```python
response = await client.delete(
    f"workspaces/{workspace}",
    params={
        "recurse": recurse
    }
```

2024-12-03 13:00 UTC, ricardogsilva commented on src/geoserverx/_async/gsx.py
> +        results = self.response_recognise(response.status_code)
Didn't we agree to change this to `result` (singular) instead? Or maybe this was scoped to another PR? I don't remember anymore

2024-12-03 13:00 UTC, ricardogsilva commented on src/geoserverx/_async/gsx.py
> +        responses = await Client.put(
Sorry, but I really do not remember, just leaving this as a note: did we agree to change this to a singular noun (_e.g._ `response`), or was this pushed to a subsequent PR?

2024-12-03 13:00 UTC, ricardogsilva commented on src/geoserverx/_sync/gsx.py
> +        response = Client.delete(f"workspaces/{workspace}?recurse={recurse}")
Same comment as above, please use httpx `params` with a dict instead of manually building the query string. Also, instead of defining the `Client` variable (which should be all lowercase btw) to use its value only once, please just use `self.http_client` directly

2024-12-03 13:00 UTC, ricardogsilva commented on src/geoserverx/_async/gsx.py
> +        return result
This is a nitpick (I'm leaving it here as it kind of applies to the whole codebase and not specifically to this line) but if you are not going to do anything else with the `result` variable, then don't even define it and simply return whatever `self.response_recognise()` outputs. Little by little, all these extra lines, which seem harmless, start adding up, and making the code just a bit harder to read.

2024-12-03 13:00 UTC, ricardogsilva commented on src/geoserverx/cli/cli.py
> +        ).model_dump()
Seems like there is no need to `result.model_dump()` here. You are dumping to a dict and then checking the value of the `code` key - a simpler alternative is to just use `result.code` instead. The benefit of using pydantic is that we have typed objects to work with, so resorting to converting them to dicts (which are untyped) is a step backwards.

2024-12-03 13:00 UTC, ricardogsilva commented on tests/_async/test_gsx.py
> +    workspace_name,
`workspace_name` does not need to be a test parameter here, which would make the setup of the test simpler

2024-12-03 13:00 UTC, ricardogsilva commented on tests/_async/test_gsx.py
> +    workspace_name,
`workspace_name` does not need to be a test parameter

2024-12-03 13:00 UTC, ricardogsilva commented on tests/_async/test_gsx.py
>  async def test_get_all_workspaces_validation(
What are we trying to achieve with this test?

Usually the name of a test function states the purpose of the test. In this case `test_get_all_workspaces_validation` is a bit mysterious to me and I do not understand what is being tested. 

Furthermore, the current implementation just tests for the case where the remote GeoServer does not have the `/workspaces` API path (I guess it would be the only way a request for `/workspaces` returns an **HTTP 404 - Not found** error), which I guess would be an indication that either the base URL of GeoServer is wrong or that it would be a very old GeoServer remote. This could be a valid test, but it seems like a weird thing to test as the only test case included in this PR.

2024-12-03 13:00 UTC, ricardogsilva commented on tests/_async/test_gsx.py
> +        ("sfsf", 404, {"error": "not found"}, "Result not found"),
In addition to this _not found_ response, it would be interesting to have a case where an actual mocked workspace representation is used, in order to test a successful interaction.

2024-12-03 13:00 UTC, ricardogsilva commented on tests/_sync/test_gsx.py
> +    assert response.code == status_code
Same comment as above on me not really understanding the purpose of this test

2024-12-03 13:00 UTC, ricardogsilva commented on tests/cli/test_cli.py
> +    assert str(status_code) in result.stdout
Same comment as above on me not really understanding the purpose of this test

2024-12-24 16:46 UTC, ricardogsilva requested changes
Almost done.

Thanks for your patience :wink:

2024-12-24 16:46 UTC, ricardogsilva commented on docs/pages/async/workspace.md
> +
This sentence is not very clear. 

As a general remark, I think the current state of these docs is a bit too verbose. They have too much text, sometimes with unclear wording.

How about a more succinct approach, with less words and more examples, like this:

> ## Get single workspace
>
> Fetches workspace details.
>
> Parameters
> - `name` (str) - Workspace name
>
> Returns
> 
> {whatever this returns}
> 
> Example
> 
> {provide an example usage where both the function call and its response are visible}

Another general remark, (which we can address in a subsequent PR) do we really need sync and async versions of the docs when the API is almost the same in both cases?

2024-12-24 16:46 UTC, ricardogsilva commented on docs/pages/sync/workspace.md
> +    To start using `geoserverx` in Sync mode, create a new instance of `SyncGeoServerX` Class, ream more about it [here](https://geobeyond.github.io/geoserverx/pages/sync/)
```suggestion
    To start using `geoserverx` in Sync mode, create a new instance of `SyncGeoServerX` Class, read more about it [here](https://geobeyond.github.io/geoserverx/pages/sync/)
```

2024-12-24 16:46 UTC, ricardogsilva commented on docs/pages/sync/workspace.md
> +| isolated | :negative_squared_cross_mark: | `False` |`bool`      |  To define whether to keep workspace as default or not |
```suggestion
| Name | :white_check_mark: | | `str`      |  workspace name  |
| default | :negative_squared_cross_mark: | `False` | `bool`      |  whether to keep workspace as default |
| isolated | :negative_squared_cross_mark: | `False` |`bool`      |  set workspace as being isolated |
```

2024-12-24 16:46 UTC, ricardogsilva commented on src/geoserverx/cli/cli.py
> +    output: str = typer.Option("table", help="Output format - 'json' or 'table'"),
Let's use an `enum` instead of a string. Check the typer docs:

https://typer.tiangolo.com/tutorial/parameter-types/enum/

2024-12-24 16:46 UTC, ricardogsilva commented on src/geoserverx/cli/cli.py
> +                print(json.dumps(result.model_dump(), indent=2))
pydantic's [model_dump_json()](https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.model_dump_json) is able to indent: 

```suggestion
                print(result.model_dump_json(indent=2))
```

2024-12-24 16:46 UTC, ricardogsilva commented on src/geoserverx/cli/cli.py
> +                    typer.secho(result.response, fg=typer.colors.RED)
I don't remember if we had previously agreed on using rich's `print()` function instead of `typer.secho`, but let's do that

2024-12-24 16:46 UTC, ricardogsilva commented on tests/cli/test_cli.py
> +        assert workspace["name"] in result.output
This part seems overly complex.

You define the `WORKSPACE_TEST_CASES` global variable (which by the way, has a name which is not very clear) and then you use it to create the `workspace_response` pytest fixture, which in turn gets sent as an input to the `test_get_all_workspaces_success` test case and then inside this test case you compare results against the value of the global variable.

I suggest just defining the test case function and not using any global variables or fixtures here - just define the values that you need inside the test case.

2024-12-24 16:47 UTC, ricardogsilva commented on docs/pages/async/workspace.md
> +
For the sake of practicality, let's just fix this single sentence now and then we can submit a PR later, fixing all docs.

2024-12-24 16:48 UTC, ricardogsilva commented on src/geoserverx/cli/cli.py
> +    output: str = typer.Option("table", help="Output format - 'json' or 'table'"),
This comment applies to all places where this new `output` parameter is used, not just in this specific place - be sure to change them all

2024-12-24 16:48 UTC, ricardogsilva commented on src/geoserverx/cli/cli.py
> +                print(json.dumps(result.model_dump(), indent=2))
This comment applies to all places where this new output parameter is used, not just in this specific place - be sure to change them all

2024-12-24 16:50 UTC, ricardogsilva commented on src/geoserverx/cli/cli.py
> +                    typer.secho(result.response, fg=typer.colors.RED)
This comment applies to all places where `typer.secho` or `typer.echo` are used, not just in this specific case - be sure to change them all

2024-12-26 05:05 UTC, krishnaglodha commented on docs/pages/async/workspace.md
> +
I'm putting `Fetches workspace details based on name` for now ?

2025-01-02 11:58 UTC, merged